swagger: "2.0"
info:
  title: Users API
  description: API para la gestión de usuarios
  version: 1.0.0
paths:
  /users/me:
    get:
      summary: Obtiene el usuario autenticado
      parameters:
        - $ref: "#/parameters/AuthorizationHeader"
      responses:
        "200":
          description: OK
  /users:
    post:
      summary: Crea un nuevo usuario
      parameters:
        - name: user
          in: body
          description: Datos del usuario a crear
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "201":
          description: Creado
    get:
      summary: Obtiene todos los usuarios
      parameters:
        - $ref: "#/parameters/AuthorizationHeader"
      responses:
        "200":
          description: OK
  /users/{id}:
    get:
      summary: Obtiene un usuario por su ID
      parameters:
        - name: id
          in: path
          description: ID del usuario
          required: true
          type: integer
        - $ref: "#/parameters/AuthorizationHeader"
      responses:
        "200":
          description: OK
    put:
      summary: Actualiza un usuario por su ID
      parameters:
        - name: id
          in: path
          description: ID del usuario
          required: true
          type: integer
        - name: user
          in: body
          description: Datos del usuario a actualizar
          required: true
          schema:
            $ref: "#/definitions/User"
        - $ref: "#/parameters/AuthorizationHeader"
      responses:
        "200":
          description: OK
    delete:
      summary: Elimina un usuario por su ID
      parameters:
        - name: id
          in: path
          description: ID del usuario
          required: true
          type: integer
        - $ref: "#/parameters/AuthorizationHeader"
      responses:
        "204":
          description: Sin contenido
parameters:
  AuthorizationHeader:
    in: header
    name: Authorization
    description: Token de autorización
    required: true
    type: string
definitions:
  User:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      password:
        type: string
